import { ThemeToggle } from "@/components/ThemeToggle";
import { StarBackground } from "@/components/StartBackground";
import { NavBar } from "@/components/NavBar";
import { HeroSection } from "@/components/HeroSection";
import { AboutSection } from "@/components/AboutSection";
import { SkillsSection } from "@/components/SkillsSection";
import {ContactSection} from "@/components/ContactSection";
import { Footer } from "../components/Footer";

export const Home = () => {
  return (
    <><head>
      <title>George Fligil</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <meta name="author" content="George Fligil" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta name="keywords" content="Portfolio, Developer, George Fligil, Software Engineer, Web Development, React, JavaScript, Frontend, Backend, Fullstack, SAS, Python, C#" />
      <meta name="apple-mobile-web-app-capable" content="yes" />
      <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
    </head>
    <div className="min-h-screen bg-background text-foreground overflow-x-hidden">

        {/* Theme Toggle*/}
        <ThemeToggle />

        {/* Background Effects*/}
        <StarBackground />

        {/* NavBar*/}
        <NavBar />

        {/* Main Content */}
        <main>
          <HeroSection />
          <AboutSection />
          <SkillsSection />
          <ContactSection />
        </main>

        {/* Footer*/}
        <Footer />

      </div></>
  );
};
